stats/urls.py
from django.conf.urls import url

import stats.views

urlpatterns = [
    url(r'^$', stats.views.stats_home, name='stats-home'),
    url(r'^entries/$', stats.views.unique_entries, name="stats-unique-entries"),
    url(r'^refs/$', stats.views.last_referers, name="stats-referers"),
    url(r'^google/$', stats.views.google_search_keywords, name="stats-google"),
    url(r'^delete/$', stats.views.delete_all, name="stats-delete-data"),
    url(r'^mobile/$', stats.views.log_mobile_device),
    url(r'^mobile_devices/$', stats.views.mobile_devices, name="stats-mobile-devices"),
]

stats/models.py
from django.db import models


class Stat(models.Model):
    ip = models.GenericIPAddressField()
    referer = models.TextField(blank=True)
    date = models.DateField(auto_now_add=True)
    site = models.ForeignKey('sites.Site')

    class Meta:
        verbose_name = 'Stats'
        verbose_name_plural = 'Stats'

    def __unicode__(self):
        return self.referer


class Mobile(models.Model):
    ip = models.GenericIPAddressField()
    date = models.DateField(auto_now_add=True)
    created = models.DateTimeField(auto_now_add=True)
    user_agent = models.CharField(max_length=255)
    window_width = models.IntegerField(blank=True, null=True)
    window_height = models.IntegerField(blank=True, null=True)
    screen_width = models.IntegerField(blank=True, null=True)
    screen_height = models.IntegerField(blank=True, null=True)
    device_pixel_ratio = models.CharField(max_length=10, blank=True)

    class Meta:
        verbose_name = 'Mobile'
        verbose_name_plural = 'Mobile'

    def __unicode__(self):
        return self.user_agent

stats/templates/stats/entries.html
{% extends "admin/index.html" %}
{% load i18n %}

{% block content %}
<div id="content-main">
<div class="module">
    <h2>{% trans "Sites total entries" %}</h2>
    <ul>
    {% for site in sites %}
        <li><b>{{ site.name }}</b>: {{ site.stat_set.count }}</li>
    {% endfor %}
    </ul>

    <h2>{% trans "Daily entries" %}</h2>
    <ul>
    {% for entry in daily_stats %}
        <li><b>{{ entry.date }}</b>: {{ entry.hits }}</li>
    {% endfor %}
    </ul>
</div>
</div>
{% endblock %}


{% block sidebar %}
{% include "stats/partials/sidebar.html" %}
{% endblock %}

stats/templates/stats/google.html
{% extends "admin/index.html" %}
{% load i18n %}

{% block content %}
<div id="content-main">
<div class="module">
    <h2>{% trans "Google Keywords" %}</h2>
    <ul>
        {% for keyword, count in keywords %}
            <li><b>{{ keyword }}</b>: {{ count }}</li>
        {% endfor %}
    </ul>
</div>
</div>
{% endblock %}


{% block sidebar %}
{% include "stats/partials/sidebar.html" %}
{% endblock %}

stats/templates/stats/home.html
{% extends "admin/index.html" %}
{% load i18n %}

{% block content %}
---
{% endblock %}


{% block sidebar %}
{% include "stats/partials/sidebar.html" %}
{% endblock %}

stats/templates/stats/mobile_report.html
{% extends "admin/index.html" %}
{% load i18n %}

{% block content %}
<div id="content-main">
<div class="module">
<h2>{% trans "General" %}</h2>
<ul>
    <li><b>{% trans "Unique USER_AGENTs" %}</b>: {{ distinct_user_agents_count }}</li>
    <li><b>{% trans "Entries total" %}</b>: {{ total_entries.all_entries }}</li>
    <li><b>{% trans "iPad entries" %}</b>: {{ total_entries.ipad_entries }}</li>
    <li><b>{% trans "iPhone entries" %}</b>: {{ total_entries.iphone_entries }}</li>
    <li><b>{% trans "iPod entries" %}</b>: {{ total_entries.ipod_entries }}</li>
    <li><b>{% trans "Android entries" %}</b>: {{ total_entries.android_entries }}</li>
    <li><b>{% trans "S60 entries" %}</b>: {{ total_entries.s60_entries }}</li>
    <li><b>{% trans "Bada entries" %}</b>: {{ total_entries.bada_entries }}</li>
    <li><b>{% trans "Blackberry entries" %}</b>: {{ total_entries.blackberry_entries }}</li>
</ul>
</div><div class="module">
<h2>{% trans "Android" %}</h2>
<h3>{% trans "Browsers" %}</h3>
<ul>
    <li><b>Webkit</b>: {{ android_browsers.webkit }}</li>
    <li><b>Opera</b>: {{ android_browsers.opera }}</li>
    <li><b>Firefox</b>: {{ android_browsers.firefox }}</li>
</ul>
<h3>{% trans "Device types" %}</h3>
<ul>
    <li><b>{% trans "Phones" %}</b>: {{ android_devices.phones }} ({% trans "resolution below 640x480 / 480x640" %})</li>
    <li><b>{% trans "Tablets" %}</b>: {{ android_devices.tablets }}</li>
</ul>
<h3>{% trans "System versions" %}</h3>
<ul>
    {% for version, hits in android_versions.items %}
        <li><b>{{ version }}</b>: {{ hits }}</li>
    {% endfor %}
</ul>
</div><div class="module">
<h2>{% trans "Popular screen resolutions" %}</h2>
<ul>
    {% for entry in resolutions.all %}
        <li><b>{{ entry.screen_width }}x{{ entry.screen_height }}</b>: {{ entry.wcount }}</li>
    {% endfor %}
</ul>
<h2>{% trans "Popular resolutions for Android devices" %}</h2>
<ul>
    {% for entry in resolutions.android %}
        <li><b>{{ entry.screen_width }}x{{ entry.screen_height }}</b>: {{ entry.wcount }}</li>
    {% endfor %}
</ul>
</div></div>
{% endblock %}


{% block sidebar %}
{% include "stats/partials/sidebar.html" %}
{% endblock %}

stats/templates/stats/referers.html
{% extends "admin/index.html" %}
{% load i18n %}

{% block content %}
<div id="content-main" style="width: 800px; font-size: 13px;">
<div class="module">
    <h2>{% trans "Last Referers" %}</h2>
    <ul>
        {% for referer in object_list %}
            <li style="line-height: 1.5em;"><a href="{{ referer|striptags|escape }}" target="_blank">{{ referer|striptags|escape }}</a></li>
        {% endfor %}
    </ul>
</div>
</div>
{% endblock %}


{% block sidebar %}
{% include "stats/partials/sidebar.html" %}
{% endblock %}